### ISSUE TITLE
Label discrepancy

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/ClubExcellence#11]
When you go to ‘Manage Tasks’ and click the eye icon to view a task, the due dates read ‘SEASON_START’, ‘YEAR’, ‘PRESEASON_START’, etc. In the admin view, I see ‘End of Pre-Season’, ‘Season Month 8’ etc. Can the user view be displayed the same way as the admin view?

**Comment by sn-np** [comment]
Fixed.
