### ISSUE TITLE
Impersonate User

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/ClubExcellence#12]
The ‘impersonate user’ option in the user profile is not working. I get a message that says ‘Impersonating this user is forbidden’

**Comment by sn-np** [comment]
Which person are you attempting to impersonate? 

Not all accounts can be impersonated. For example, on live, Susan Hunt may never be impersonated, and in this dev environment the Neural Planet user may not be impersonated. However, you should be able to impersonate the secretary (for example).

**Comment by cameroneickmeyer** [comment]
Trying to impersonate CX Admin. Should that be allowed? Here's a bug we found:

Tried to impersonate the NP user, was blocked, then attempted to impersonate the president and was told "you are already impersonating a user" ... however if we started FIRST with the president it works.

**Comment by sn-np** [comment]
Where are you offered the ability to impersonate cxadmin@neuralplanet.com? 

I'm not able to replicate the block and then impersonate. Can you give me a sequence of steps? Note that if you are impersonating someone, the header on the page updates (it'll actually show both the person you are impersonating and your actual login).

**Comment by cameroneickmeyer** [comment]
We aren't offered that ability. Sorry for the confusion. Logged in as CX Admin we can't impersonate the NP users. That seems correct. 

Step 1: Attempt to impersonate NP user, hit error
Step 2: Go back to user list
Step 3: Attempt to impersonate President, hit error
