### ISSUE TITLE
Bug/Request: Two step change access

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/ClubExcellence#16]
Presently changing a user from Enabled to Disabled is a single click. Can we have a confirmation popop/screen appear?

"Are you sure you want to change this user (Display user's name/email) to disabled/enabled?"

**Comment by sn-np** [comment]
Are YOU sure you really want that? It is a single click to switch it back too, which means that most of the time a single click is good, and in the off case an error is made, only then is an additional click required.

**Comment by sn-np** [comment]
Nevermind. In thinking further I realized the confirmation version is more consistent with other pieces of the system. I'll add it to the punch list

**Comment by sn-np** [comment]
Two-step is now in place.
