### ISSUE TITLE
Bug: Editing User Account Info

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/ClubExcellence#18]
I’m getting an error when editing a user’s account information. It says, ‘There was an error saving the User’s settings: Access Denied’.

- Logged in as cxadmin, tried editing my test user and Andy’s in both the 17-18 and 18-19 seasons

- Also tried changing the password, received the same error

**Comment by cameroneickmeyer** [comment]
"my test user" is Brittany's FYI

**Comment by sn-np** [comment]
Abba fixed a setting. It should go through now.
