### ISSUE TITLE
Bug: Deleting Custom Role

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/ClubExcellence#22]
When deleting a custom role from TST0001, I received the following error which proved to be a dead end prohibiting me from accessing CX within the association. This action broke TST0001 CX for the President, Secretary, and Admin. This applies to both the 2017-18 and 2018-19 season. The Read-Only version still works. I confirmed with Brittany that my action on the server broke TST0001 for her as well. This was done within Windows on Google Chrome. Please see the screenshot below for the text that pops up. I can not replicate the scenario in another association as of yet.

cid:image005.jpg@01D3C0FD.445DE760

**Comment by cameroneickmeyer** [comment]
![snipimage](https://user-images.githubusercontent.com/27363244/37722079-d6d31e12-2cf0-11e8-9451-67e6975a23d5.JPG)

**Comment by sn-np** [comment]
Do you happen to remember if it was an old or new custom task that you were attempting to delete? Or even the nature of the task itself?

**Comment by cameroneickmeyer** [comment]
This was a role, not a task, but he doesn't remember which one it was, however it was already there so not created.

**Comment by sn-np** [comment]
We believe this is fixed. However, the error trace shown in the second comment appears completely unrelated. Can you confirm that you just inserted the wrong picture?

**Comment by cameroneickmeyer** [comment]
I put in the right image that was sent to me.

**Comment by sn-np** [comment]
Who sent it? Is it possible that they sent the wrong image in the first place?

**Comment by cameroneickmeyer** [comment]
Andy. He says "100% sure. It came up every time we clicked on “Club Excellence” from the Red Navigation bar in any position trying to access TST0001."

**Comment by sn-np** [comment]
The original issue had to do with limiting deletion of custom roles to those which were only assigned to one user. If the role was assigned to multiple users, the error was generated. This has been fixed.

**Comment by sn-np** [comment]
The original issue had to do with a limitation on the deletion of custom roles. This has been fixed.
