### ISSUE TITLE
Bug - President/Admin issue

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/ClubExcellence#23]
I caught a bug when proceeding as a CX Admin after logging in as President. After selecting an association from the CX Associations List I am getting the following error when trying to “View Past Events” under the “Try Hockey For Free Events” section of the association profile:
 
"Access denied: events/admin/programs/2
 
When I log in as the CXAdmin and make the same selection (CX Admin), I am able to follow the same process as above but view past Try Hockey events within the PowerPlay system. I confirmed with Brittany that she has the same experience. This was done within Google Chrome on Windows.

**Comment by sn-np** [comment]
Event hosting and administration is a separate access flag. Do you want all CX Admin's to have those abilities? Or should we add the access on a per user basis?

**Comment by cameroneickmeyer** [comment]
User error, sorry.
