### ISSUE TITLE
BUG: Task year issue

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/ClubExcellence#4]
When you add a task with an exact date, it adds the year. If you add an exact date of 10/31, the date picker says 2018, but it’s added as 2017.

**Comment by sn-np** [comment]
The exact date is a particular day and month within a season. The year is not actually stored but date picker interfaces don't give us an easy way to let us make it easy to choose the day, but not specify a year. For each association, there is one instance of the day/month combination per year, but the year associated with it could be different depending on the starting date the association choses for their season.

To make the interface clearer, we could make the user choose the month and day separately (and not have the user choose a year at all), but that is somewhat more cumbersome than choosing via a datepicker.

**Comment by cameroneickmeyer** [comment]
Can we instead suppress the display of the year? That would solve the issue, no?

**Comment by sn-np** [comment]
Does how it appears now work? The date picker still has a year on it, but it appears in the task list (and in the field once chosen) without the year.

**Comment by cameroneickmeyer** [comment]
Yes that works!
