### ISSUE TITLE
Typo: Availability Button

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/ClubExcellence#5]
The availability button has a grammatical error: Should read ‘set to sign-up available’ / ‘set to sign-up unavailable’

**Comment by sn-np** [comment]
Having trouble finding this one. What is the current wording?

**Comment by cameroneickmeyer** [comment]
Sorry, my fault. Current wording is just confusing, no typo. Can we instead be more direct with the language and go with "set to available/unavailable"?

**Comment by sn-np** [comment]
We have slightly different wording on the interface and on the confirmation. Can you please edit these as you'd like them:
**AVAILABLE -> UNAVAILABLE:**
Interface: 'You are electing to set the sign-up availability for association SDH0121 to "unavailable" for the 20172018 season.' 
Confirmation: 'Are you sure you want to disable signups for association SDH0121 for the 20172018 season?'

**UNAVAILABLE -> AVAILABLE**
Interface: 'You are electing to set the signup status for association SDH0121 to "Available for Signup" for the 20172018 season.'
Confirmation: 'Are you sure you want to enable signups for association SDH0121 for the 20172018 season?'

**Comment by cameroneickmeyer** [comment]
AVAILABLE -> UNAVAILABLE:
Interface: 'You are changing the sign-up availability for SDH0121 to "Unavailable" for the 2017-2018 season.'
Confirmation: 'Are you sure you want to remove SDH0121 from the 2017-2018 season sign-up list?'
 
UNAVAILABLE -> AVAILABLE:
Interface: 'You are changing the sign-up availability for SDH0121 to "Available" for the 2017-2018 season.'
Confirmation: 'Are you sure you want to add SDH0121 to the 2017-2018 season sign-up list?'
 
Question: the season (2017-2018) is listed. This will have to be updated every year, correct? If so, is there a way to make it generic enough that it doesn’t have to be changed (say current season or selected season)?

**Comment by sn-np** [comment]
The specific season is being dynamically generated based on the season you are managing (so no code changes will be necessary for it to update). I'll let you know when the wording changes are complete.

**Comment by sn-np** [comment]
Updated.
