### ISSUE TITLE
BUG: Information User Agreement not saving

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/ClubExcellence#6]
Each time we log in we are prompted to accept the agreement. Should be saving, correct?

**Comment by sn-np** [comment]
Originally the IUA acceptance wasn't being saved separately from the confirmation number, so if you saved a valid conf number, you also wouldn't be prompted for the IUA.  Abba updated that though, so now the IUA acceptance is stored separately from the conf number.

Please note: As with the conf #, this is stored at the user level, not the association level, so signing once will sign for the entire season.
