### ISSUE TITLE
Sorting question

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/ClubExcellence#7]
The list of associations are sorted by the most recent registration, and in the live environment it’s sorted alphabetically. Will the system continue to sort alphabetically?

**Comment by sn-np** [comment]
I believe that in the testing environment it is actually sorted with active associations first (sorted alphabetically) and then inactive associations (also alphabetical). It makes it much easier to find associations that are actually using the system, and you can get back to the original view by clicking on the column heading.

Do you want to revert to the old way of sorting?

**Comment by cameroneickmeyer** [comment]
We'll stick with this new sorting format. Thanks for the clarification!
